### ISSUE TITLE
Duplicated validation functions in DensePoseConfig

### ISSUE THREAD

**Issue by pjbull** [drivendataorg/zamba#146]
`get_filepaths` and `validate_files` are copied from the methods on the `PredictConfig`

We should refactor so both use the same codepaths.

--------------------

can we import these duplicated validation functions from `zamba.models.config.py`

_Originally posted by @ejm714 in https://github.com/drivendataorg/zamba/pull/142#discussion_r733331428_

**Comment by ejm714** [comment]
This was a bonus fix in https://github.com/drivendataorg/zamba/pull/247
