### ISSUE TITLE
Avoid using the entire path as part of the cache key

### ISSUE THREAD

**Issue by AllenDowney** [drivendataorg/zamba#201]
Relevant LOC: https://github.com/drivendataorg/zamba/blob/master/zamba/data/video.py#L359\

This line of code uses the path of the input video file as part of the path to the cached data. This path, along with the hashed configuration, effectively behaves like the cache key; that is, in order to find something in the cache, we need the same path and the same hashed configuration.

The problem is that the path contains both unique identification of the video (which is good) and also some specific information about the file system where the video is (which is bad).

For example, if the video is in an S3 bucket which is mounted on a mount point called `data`, we might see a path like this:

`s3://drivendata-client-zamba/data/raw/european/HT_T30/Left_cam47/HT_cam47_432058_5888835_20190828/08280126.MP4`

In that case, the path that's used in the cache key is

`data/raw/european/HT_T30/Left_cam47/HT_cam47_432058_5888835_20190828/08280126.MP4`

In this example, the `data/raw` part of the path should not be part of the key, because if someone else happens to mount the same bucket on a different mount point, and they look up this video, they would not find the cached data, and if they processed the video, the cached data would go in a different location.

A solution would be to strip off the part of the path prior to the geography, which we know is the beginning of the unique identifier of the video. The only sticky point is that this part of the code would need access to a complete list of geographies, which could change over time.

**Comment by ejm714** [comment]
> A solution would be to strip off the part of the path prior to the geography, which we know is the beginning of the unique identifier of the video. 

The tricky thing here IMO is knowing which part to strip off, as this can arbitrary for users.

We do let users specify the `cache_dir` in the video loader config (this is where zamba will go looking for the cache). Maybe there's additional functionality we provide in setting up a symlink that matches the original location of the videos in the cache to make the lookup smoother?

**Comment by AllenDowney** [comment]
As a followup on this, it looks like `cache_dir` is also used as part of the key, so someone using the cache has to make sure the path to the data is the same as when the cache was made. The best fix would be to omit `cache_dir` from the key.

**Comment by ejm714** [comment]
Fixes here should be:
- [ ] omit `cache_dir` from the key
- [ ] do not modify config object that is passed in
