### ISSUE TITLE
Speed up or eliminate checking filepaths

### ISSUE THREAD

**Issue by AllenDowney** [drivendataorg/zamba#216]
This step is super slow

```
Checking all 245,944 filepaths exist. Can take up to a minute for every couple thousand files.
```

Looking it utilization while it's running, `goofys` is using about 20% of a CPU, which suggests it's doing ridiculous I/O to AWS. There's gotta be a better way (or at least an option to skip it).

**Comment by ejm714** [comment]
It looks like we do this with pandas path currently: https://github.com/drivendataorg/zamba/blob/17d291b3a6074e85d7ad8b980ef7837d0fd00821/zamba/models/config.py#L107

Can we significantly speed this up if we use `pqdm` to parallelize the check?
