### ISSUE TITLE
Can zamba be used on photos as well as videos?

### ISSUE THREAD

**Issue by VLucet** [drivendataorg/zamba#225]
Hello, very cool tool! I was wondering if you could detail the capabilities of zamba (and zamba cloud) for camera traps images (ie static, not videos). My apologies if that is in the doc, I have read as best as I could but did not see it.

**Comment by ejm714** [comment]
Hi @VLucet! Currently zamba and Zamba Cloud only support videos, though we may support images in the future. 

Here are some other tools that currently focus on camera trap images:
- [MegaDetector](https://github.com/microsoft/CameraTraps/blob/main/megadetector.md) -> detects animals, people, and vehicles in camera trap images. Does not do species classification
- [Wildlife Insights](https://www.wildlifeinsights.org/) -> platform for species classification on camera trap images

**Comment by VLucet** [comment]
Thanks for your reply @ejm714 !
