### ISSUE TITLE
Remove anaconda Windows link from installation documentation, which can be misleading

### ISSUE THREAD

**Issue by lakik** [drivendataorg/zamba#294]
Hi trying to install zamba but it stops with this ERROR: Failed building wheel for yolox. I tried to install it separately but it fails too. Any hints?
Thank you!

**Comment by pjbull** [comment]
Can you share:
 - More of the logs so we can see what actually went wrong when trying to build
 - The operating system you are on
 - The version of Python you are on

**Comment by lakik** [comment]
Hi My OS is Win11 and Python version is 3.9.12.

The log you will find in the attached file
[Zamba_install.txt](https://github.com/drivendataorg/zamba/files/12794401/Zamba_install.txt)

**Comment by pjbull** [comment]
Hi @lakik, unforunately as noted in the docs, installation is not supported directly on Windows: https://zamba.drivendata.org/docs/stable/#installing-zamba

We recommend [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install) as a way to run the linux version of the tools on your Windows machine, which is supported.

**Comment by lakik** [comment]
That is a pity. 
But please do not provide a link to an installation video for anaconda on windows on the installation site. This is misleading.

**Comment by pjbull** [comment]
That's a good point, I'll update this issue to reflect removing that link.

**Comment by lakik** [comment]
Unfortunately I encounter the identical problem also on wsl ubuntu with  python version 3.11.5.. Is the later the reason? Is version 3.8 or 3.9 the only one which is working?

**Comment by lakik** [comment]
than please put not the link to the main page of anaconda because there you will find only the latest version. Please link to the archive and best to the version you will need for zamba. 
Thank you.

**Comment by lakik** [comment]
Again the installation failed
with WSL ubuntu 16.4. anaconda python 3.9.12 and failed with installing yolox again.
this is the log
[Zamba_install_ubuntu.txt](https://github.com/drivendataorg/zamba/files/12846646/Zamba_install_ubuntu.txt)
Do you have any idea how to solve this?

**Comment by pjbull** [comment]
That error indicates that the build is looking for the executable `g++`, which is not present on your ubuntu system. `g++` is commonly available in the `buid-essentials` package, which you can install in Ubuntu:

```bash
sudo apt update && sudo apt install build-essential
```

--------------------------------------

As a side note, these errors are generic configuration problems with the environment, and not particular to the Zamba package. You can usually get fast and accurate next steps by googling the error text or using chatgpt, which can help you move forward without waiting for a response.

**Comment by pjbull** [comment]
Thanks for the feedback @lakik.

We'll add some notes based on this thread, but it's not really feasible to cover all the different machine configurations that someone could start with cross referenced with all the dependencies of our dependencies. For example, some Ubuntu images and other distributions come with `build-essentials` or another C++ compiler already.

**Comment by lakik** [comment]
Hi Peter,
unfortunately with all the searching and trying I can't get it to run. I got a little further, but some error messages are mutually exclusive or can not be implemented because some parts can not be uninstalled to install the required versions. This is a bit frustrating because I wanted to start to use it. 
If you have any hints, please let me know.
Thanks

**Comment by pjbull** [comment]
@lakik Sorry, I know it's probably frustrating, but there's no specific help I can provide unless you attach the information about your system and the output logs. That's a best practice any time you file a bug in a GitHub repo, and it allows maintainers to be as helpful as possible.

The test suite runs weekly to ensure the package can be installed on ubuntu (e.g., see this [build from last week](https://github.com/drivendataorg/zamba/actions/runs/6383958472/job/17325633459)). This means that we're confident it can be installed on Ubuntu.

Another option would be to run on top of docker. For example, here are the commands that we run on top of the `pytorch/pytorch:1.11.0` base image (which I believe is ubuntu based). A number of the installed packages are used for other purposes and are not strictly required, but may help you.

```
apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:savoury1/ffmpeg4 && \
    apt-get update && \
    apt-get -y install \
    build-essential \
    ffmpeg \
    git \
    libavcodec-dev \
    libavdevice-dev \
    libavfilter-dev \
    libavformat-dev \
    libavutil-dev \
    libsm6 \
    libswresample-dev \
    libswscale-dev \
    libxext6 \
    pkg-config \
    wget \
    x264 \
    x265 && \
    rm -rf /var/lib/apt/lists/*

pip install \
    torch==1.11.0 \
    https://github.com/drivendataorg/zamba/releases/latest/download/zamba.tar.gz
```

**Comment by lakik** [comment]
Thank you again. the build from last week is based on the latest ubuntu, again the installation guide is not really up to date. 
I will try again with the latest ubuntu.

**Comment by lakik** [comment]
Finnaly it worked and Zamba is running. :)

**Comment by pjbull** [comment]
Glad to hear that. Sorry for the frustrations, we've updated the documentation per your comments above: https://github.com/drivendataorg/zamba/pull/299

If you have any other particulars from your experience to add, please chime in.
