### ISSUE TITLE
Update dependencies to work with newer versions of Python

### ISSUE THREAD

**Issue by pjbull** [drivendataorg/zamba#86]
The current pinned versions work with Python 3.6, but we should support 3.7+ going forward.

**Comment by jayqi** [comment]
Some observations about how the dependencies are set up. 

- Do the dependencies need to be strictly pinned? If this is the type of package that other projects need to depend on, having pinned dependencies make it really hard to resolve zamba's dependencies against other package's dependencies. 
- If pinning is important, then this would be a good use case for [pip-tools](https://github.com/jazzband/pip-tools). It will make it easier to update pinned dependencies in the future. 

@pjbull @tamara-glazer
